### ISSUE TITLE
Doesn't work on Odin lite

### ISSUE THREAD

**Issue by Orion81** [langerhans/OdinTools#15]
Android 11 stock, try to install and error package.
It is an amazing app, can you make it compatible with old odin?

**Comment by langerhans** [comment]
There are probably a lot of differences to the old Odin that would prevent making it work. Alas i don't have the device to even analyze if it's possible. But looking at the code for Odin 2 there is no reference to the old Odin, just to Retroid handhelds. Sorry!

**Comment by Orion81** [comment]
Thank's. I think is probably a issue with the android version, I tried to install on my redmi note 12 and no package error.
With odin lite (dimensity 900 - android 11) no way to install. Error in the package
