### ISSUE TITLE
Stops working when app is force closed

### ISSUE THREAD

**Issue by langerhans** [langerhans/OdinTools#17]
Multiple reports so far. Which is odd cause the service should be running as long as the system binds to it. Need to investigate.

**Comment by Syzygos** [comment]
I haven't seen anyone else mention this, but adding the app to 'whitelist application' under Odin settings has kept the app working for me even after turning the Odin 2 on from a complete shutdown. Even if I force close the app it'll still be running. I've mentioned it before in a reddit post, but it seemed to go unnoticed.

**Comment by langerhans** [comment]
Thanks, that's good to know. Maybe this would be a simpler workaround than what my initial plan was :D
