### ISSUE TITLE
RP4 Pro - cannot load app after reinstall

### ISSUE THREAD

**Issue by MSN23PL** [langerhans/OdinTools#26]
Steps to reproduce:
1)install the app on rp4pro
2)uninstall the app
3)install the app again
4)attempt to run the app to pull up its front-end

Observer result: 
Application is not being displayed. It seems to be running in the background as there are settings from odin tools available in the pull down menu.

**Comment by miguelguzmanr** [comment]
Hello and thank you for your report.

The latest version 1.2.1 introduces a fix for the app not launching in RP4/P devices, which seems to be the issue you're facing. Could you double-check you're running the latest version? See: https://github.com/langerhans/OdinTools/releases/tag/1.2.1

Please report back with any findings!

**Comment by MSN23PL** [comment]
Tested  build version 1.2.1 and can confirm bug is fixed. You're really nailing it with this app dude! Many thanks!
