### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by mo-amaan** [langerhans/OdinTools#39]
I have been trying to install the apk, however it keeps saying problem parsing the apk and would not install.

**Comment by Lauwh6** [comment]
I have the same problem on a RP4.
(but its working on a RP4 pro)

**Comment by miguelguzmanr** [comment]
As of today, OdinTools is designed to run on devices with Android 13 or above. The RP4 Pro has Android 13, meanwhile the non-Pro version has Android 11, which is probably the cause of this error.
