### ISSUE TITLE
App not installed as package conflicts with an existing package

### ISSUE THREAD

**Issue by Jurykov** [langerhans/OdinTools#43]
Trying to install OdinTools 1.3.1. Odin 2 Pro with software version 1.0.0.296.  As far as I know, I've never installed OdinTools before.  When I try to install the APK, it asks me 'Do you want to update this app'?  Then it fails on 'App not installed as package conflicts with an existing package.  I don't see it in the Play Store, or anywhere in the app drawer/desktop. 

The compatibility section on this page suggests that it will only work up to 1.0.0.288.  Is this a conflict with the latest version of the OS?  I see that some of the features listed on OdinTools seem to be available in the latest updates.  I would love to have the app overrides available still for some automation.

**Comment by langerhans** [comment]
I don't think I've seen this issue before. Can you check in Settings -> Apps -> See all apps if you find OdinTools there somewhere? You could also try adding OdinTools to Obtanium and check if it detects it as installed or can install it.

**Comment by Jurykov** [comment]
Turns out I did have Odin tools 1.0 installed somehow. Found it under
settings -> apps -> see all apps like your suggested. Uninstalled, then the
newest version installed just fine. Thanks for your help!
