### ISSUE TITLE
M1/M2 remap options

### ISSUE THREAD

**Issue by langerhans** [langerhans/OdinTools#7]
Allow remapping M1/M2 buttons to other keycodes.
Keys: `remap_custom_to_m1_value` & `remap_custom_to_m2_value`

**Comment by Cutsdeep** [comment]
Just a little differentiation in request, the ability to retain face button functionality at the same time as using it with m1/2 would be great.

Ie A button functionality is both A and M1

**Comment by miguelguzmanr** [comment]
- Configurable, uses [android key codes](https://www.temblast.com/ref/akeyscode.htm)
- Configuration persists after a restart
